export const DEFAULT_OPTIONS = {
  carouselSelector: null,
  slidesToShow: 1,
  slidesToScroll: 1,
  gap: 15,
  mouseDrag: true,
  showArrows: true,
  nextButtonSelector: null,
  prevButtonSelector: null,
  showScrollbar: true,
  scrollbarStyle: {
    height: 8,
    marginTop: 8,
    marginBottom: 8,
    borderRadius: 4,
    backgroundColor: "#ebebeb",
    thumbColor: "#6d6d6d",
    thumbHoverColor: "#4b4b4b",
  },
  responsive: null,
};
